# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://mikopos.github.io"

# Google tracking id
google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############

lang: "en"
author: "Marios Gavriil"
title: "{ Marios Gavriil }"
description: "Blog and website of Marios Gavriil, blogging mainly for tech and music. Opinions expressed are mine."
keywords: "marios, gavriil, personal, jekyll, theme"
favicon: "/img/favicon.ico"
################
# Header layout#
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote: "C'est la vie ... "
me-img: "/img/jetpacktocat.png"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

#######
# Blog #
########

post-preview-words: 96
paginate: 5
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "personal-jekyll-theme"

############
# Timeline #
############

events:
  - image: "/img/timeline/benevocats.png"
    date: "December 2021 - Today"
    description: "Finally, I landed in the online travel world, helping people 
    jet off to far-flung places. Four years later, I’m still happily coding my 
    way around the globe—one booking at a time!"
  - image: "/img/timeline/securitocat.jpg"
    date: "October 2020 - November 2021"
    description: "Seeking stability (and fewer coffee mugs), I joined a 
    bank as a senior engineer. Despite the mountains of paperwork, I found 
    creativity sometimes flourishes best under 24/7 audits."
  - image: "/img/timeline/fintechtocat.png"
    date: "November 2019 - August 2020"
    description: "I jumped into fintech, fully expecting a rocket ship 
    to the moon—until the bills piled up faster than my pull requests. 
    It went bankrupt, but I walked away with a story to tell and an 
    impressive coffee mug collection!"
  - image: "/img/timeline/mona-the-rivetertocat.jpg"
    date: "January 2019 - November 2019"
    description: "I moved on to public sector projects and discovered 
    that bureaucracy can outsmart even the cleanest code. At least 
    I became a pro at coding through red tape!"
  - image: "/img/timeline/spidertocat.png"
    date: "June 2016 - December 2018"
    description: " I started as a wide-eyed junior in telecom, 
    convinced my code would save the world. Reality hit when I 
    realized debugging was harder than deciphering alien 
    signals—but hey, it was fun!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2009 - September 2015"
    description: "Started coding"

# First image of the Timeline
timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "mikopos@gmail.com"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb:
  "Marios Gavriil is an awesome person. He lives between Jigglypuffs and Deadpools figures and loves unicorns. 
   In his spare time composing music or experimenting new recipes in the kitchen"
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - icon: "github"
    url: "https://github.com/mikopos"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/marios-gavriil"
  - icon: "soundcloud"
    url: "https://soundcloud.com/marios-denleo"
  - icon: "rss"
    url: "https://mikopos.github.io/feed.xml"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
